//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileCompanyApplication.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderHasProduct = new HashSet<OrderHasProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public int ProductUnitOfMeasurementID { get; set; }
        public decimal ProductPrice { get; set; }
        public byte ProductMaxDiscount { get; set; }
        public int ProductManufacturerID { get; set; }
        public int ProviderID { get; set; }
        public int ProductCategoryID { get; set; }
        public byte ProductCurrentDiscount { get; set; }
        public int ProductAmount { get; set; }
        public string ProductInfo { get; set; }
        public string ProductImage { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHasProduct> OrderHasProduct { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
    }
}
